### ISSUE TITLE
Value function in Prospect Theory

### ISSUE THREAD

**Issue by brshallo** [R-CoderDotCom/econocharts#4]
I think the value function from [Prospect Theory](https://en.wikipedia.org/wiki/Prospect_theory) would be a good addition:

![](https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Loss_Aversion.png/1024px-Loss_Aversion.png)

(Wrote a recent [post](https://www.bryanshalloway.com/2020/10/28/idea-for-casino-games-where-the-player-almost-always-win/) that touched briefly on Prospect Theory and couldn't find any R packages for making a quick example chart...)

**Comment by R-CoderDotCom** [comment]
Hey there! Thanks for the suggestion.

I wrote the following function:

```r
ptvalue <- function(x, sigma, lambda, main = NULL, sub = NULL, xlab = NULL, ylab = NULL, bg.col = "white"){

  if(missing(x)) {

    x <- seq(-100, 100, 0.01)
  }

  if(missing(sigma)) {
    sigma <- 0.88
  }

  if(missing(lambda)) {
    lambda <- -2.25
  }

  # Tversky & Kahneman, 1992
  value <- function(x, sigmaf = sigma, lambdaf = lambda) {

    if (x >= 0) {
      return(x ^ sigmaf)
    }

    if (x < 0) {
      return(lambdaf * (-x) ^ sigmaf)
    }
  }

  value <- Vectorize(value, vectorize.args = "x")

  ggplot(data = tibble(x = x), mapping = aes(x)) +
    stat_function(fun = value, size = 1) +
    labs(x = xlab, y = ylab, title = main, subtitle = sub) +
    geom_hline(yintercept = 0) +
    geom_vline(xintercept = 0) +
    theme(plot.title = element_text(size = rel(1.3)),
          axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0), angle = 0, vjust = 1),
          axis.title.x = element_text(margin = margin(t = 0, r = 25, b = 0, l = 0), angle = 0, hjust = 1),
          plot.background = element_rect(fill = bg.col),
          plot.margin = margin(0.5, 1, 0.5, 0.5, "cm"))

}

# Example
ptvalue(sigma = 0.26)
```

Which results into: 

![imagen](https://user-images.githubusercontent.com/67192157/100869107-d8192080-349c-11eb-8431-6443c746a6b0.png)


I'm not very familiar with Prospect Theory, so I would like to know if I'm missing something before continuing improving the function.

I will also try to add an argument to add the intersections automatically.

**Comment by R-CoderDotCom** [comment]
Update


```r
ptvalue(sigma = 0.25, col = 1, xint = 50, xintcol = 4)
```

![imagen](https://user-images.githubusercontent.com/67192157/100878081-fdf8f200-34a9-11eb-8865-b25f3ab2cf0a.png)

**Comment by brshallo** [comment]
Very nice (I am no expert on Prospect Theory though). One thing I might add is that it may be worth adding the x-axis labels of "Loss" and "Gain" and the y-axis label of "Value" to the default (or something that conveys these).

It's also tempting to suggest including a chart on [expected utility](https://en.wikipedia.org/wiki/Expected_utility_hypothesis) which, for context, Prospect Theory aims to fix some of the holes of...

![](https://kevinbinz.files.wordpress.com/2016/10/prospect-theory-evolution-of-utility-function-3.png?w=788)

Example:

![](https://www.economicshelp.org/wp-content/uploads/2017/03/utlity-function-risk-aversion.jpg)
---

Somewhat separate from the issue but I notice you use an `if(missing(var))` approach for filling in unspecified arguments in the function's formals. I am curious why you use this approach rather than specifying default values in the arguments? i.e.

`ptvalue <- function(x = seq(-100, 100, 0.01), sigma = 0.88, lambda = -2.25, main = NULL, sub = NULL, xlab = NULL, ylab = NULL, bg.col = "white"){
...
}`

Is there a reason to use the `if(missing(var))` approach in some scenarios to set defaults or is this more just a stylistic difference...? (feel free to DM me [@brshallo](https://twitter.com/brshallo) if this is too off-topic here...)

**Comment by R-CoderDotCom** [comment]
Hi, there is no specific reason why I used `missing` instead of specifying the values. I just wrote the function quickly and I didn't think about it. The `missing` function is useful when the argument is optional, like the `xint` argument. (take a look to the function I just uploaded).

However, I will mantain the `missing` function for the argument `x`, due to the X-axis values are not generally specified by default when writing functions (see `dnorm`, for example) but I want my graphical functions to create a default plot when no argument is specified without loosing the styling.


I updaded the function and now you can also specify to display or not the axis ticks with the `tick` argument and the axis tick labels with the `xlabels` and `ylabels` argument. You can also customize the distance between the ticks with the `by_x` and `by_y` arguments, that default to 10 for the X-axis and to 20 for the Y-axis.

```r
ptvalue(col = 2, xint = seq(10, 80, 10), xintcol = 4, main = "Prospect Theory Value Function")
```

![imagen](https://user-images.githubusercontent.com/67192157/101016109-9b1a6000-3568-11eb-9e70-f19612bd1032.png)

It would be awesome if you could make a pull request completing the documentation of the function, as I don't have the enough time to do it now.

I will also take into account your new proposal. Thanks.

**Comment by brshallo** [comment]
With #10 still need to hit build so that documentation I added will show-up in .rd files.

**Comment by brshallo** [comment]
Had forgotten to close this. Also, if curious, this was the section of the post where I'd used the function: https://www.bryanshalloway.com/2020/10/28/idea-for-casino-games-where-the-player-almost-always-win/#note-on-prospect-theory
