### ISSUE TITLE
Neoclassical labor supply

### ISSUE THREAD

**Issue by jhilto** [R-CoderDotCom/econocharts#5]
In the standard model the labor supply curve can be backward bending if the income effect dominates the substitution effect. Essentially this looks like a parabola with respect to the y axis, but determining the exact shape would depend on the particular maximization problem.

**Comment by R-CoderDotCom** [comment]
Looks easy. I will give it a try. As in other examples, I will need to set a "default" shape and let the users the possibility to add a custom curve. Thanks

![imagen](https://user-images.githubusercontent.com/67192157/101816170-f88e4e00-3b20-11eb-8b0b-7dd0e3f81d6a.png)

**Comment by jhilton1** [comment]
Thank you! Is this where you prefer to receive other feature suggestions, or is there a better way to send them to you?

**Comment by R-CoderDotCom** [comment]
Feel free to open new issues or sending me an email to support.rcoder@protonmail.com. With Isues it is easier to me to remember what people suggested, but I also add the suggestions  to the TODO list of the README, so send the suggestions the way you prefer

**Comment by R-CoderDotCom** [comment]
I was trying to create this chart but intersections doesn't seem to work as expected due to the shape of the curve

![imagen](https://user-images.githubusercontent.com/67192157/102340490-e4ba7000-3f96-11eb-91ec-9e3fa05cd4d5.png)

This issue can be reproduced with:

```r
curve <- data.frame(Hmisc::bezier(c(1, 9, 2),
                                  c(1, 5, 9)))
line <- data.frame(x = 0:10, y = rep(3, 11))

plot(curve$x, curve$y, type = "l")
lines(line)

int <- econocharts::curve_intersect(curve, line)
abline(v = int$x)
```

![imagen](https://user-images.githubusercontent.com/67192157/102341056-96f23780-3f97-11eb-8b67-9a9ed45c1799.png)

This happens because the curve is not a function (some values of X corresponds to 2 values of Y). Not sure that I can fix this, so if you have any idea let me know.

**Comment by R-CoderDotCom** [comment]
Maybe I can split the curve in two sections and calculate the intersections for each section. I did something similar with the Laffer curve...

**Comment by R-CoderDotCom** [comment]
I could solve the issue with the idea of my last comment.

![imagen](https://user-images.githubusercontent.com/67192157/102343496-edad4080-3f9a-11eb-93e9-b701af497eb6.png)

The function will be available soon. Thanks

**Comment by R-CoderDotCom** [comment]
The function is now available. Feel free to reopen this issue if needed or opening new ones.

![imagen](https://user-images.githubusercontent.com/67192157/102770374-570ac600-4384-11eb-9eee-b185b6b8a122.png)
